PARAMS = {
    hideSlideshow: false,
    hideGallery: false,
    hideDescription: false,
    hideLocation: false,
    hideVideoTour: false,
    hideAerialTour: false,

    backTile: '',
    backColor: '#08080C',
    foreColor: '#e8e8e8',
    panelColor: '#123',
    panelTextColor: '#e8e8e8',
    dividerColor: '#555',
    addressBackColor: '#123',
    addressForeColor: '#e8e8e8',
    detailsBackColor: '#123',
    detailsForeColor: '#e8e8e8',
    sectionHeaderColor: '#ffcc00',

    address: '1384 Oak Ridge Dr',
    city: 'Colfax CA 95713',
    price: '$215,000',
    latitude: 39.087524,
    longitude: -120.959127,
    videoTourUrl: '',
    videoAerialUrl: '',

    description: "Well maintained 2 bedroom, 1.5 bath cozy town home located in a wooded court setting with mountain atmosphere. Lovely backyard patio backs up to forested greenbelt. Cuddle up in front of the gas fireplace insert in the living room. Enjoy the roomy kitchen and dining with tons of cabinets that opens up to the back patio. Upstairs master bedroom with balcony and forested views. Large 2 car garage with epoxy sealed flooring, storage shelves, and laundry area. Whole house fan, ceiling fans, low HOA, low maintenance yard and community fitness trail. Enjoy the Sierra lifestyle with easy commute access yet close to shops, hiking, biking, lakes, rivers, and mountains.",
    bedrooms: '2',
    bathrooms: 1.5,
    squareFeet: undefined,
    lotSize: undefined,
    garage: '2',
    mls: '18017990',

    brokerLogo: './sjr.jpg',
    agentPhoto: './kathleen.jpg',
    agentName: 'Kathleen Klopson',
    agentPhone: '831-234-9148',
    agentLicense: 'Cal BRE# 01133047',
    agentEmail: 'kklopson@gmail.com',
    agentUrl: 'http://www.sierrajunction.com/3/For-Sale',
    brokerUrl: 'http://www.sierrajunction.com',
    brokerUrlName: 'www.sierrajunction.com',
    brokerLicense: '01311771',

    imageList: [
        './photos/1384OakRidge-1.jpg',
        './photos/1384OakRidge-2.jpg',
        './photos/1384OakRidge-3.jpg',
        './photos/1384OakRidge-4.jpg',
        './photos/1384OakRidge-5.jpg',
        './photos/1384OakRidge-6.jpg',
        './photos/1384OakRidge-7.jpg',
        './photos/1384OakRidge-8.jpg',
        './photos/1384OakRidge-9.jpg',
        './photos/1384OakRidge-10.jpg',
        './photos/1384OakRidge-11.jpg',
        './photos/1384OakRidge-13.jpg',
        './photos/1384OakRidge-13.jpg',
        './photos/1384OakRidge-14.jpg',
        './photos/1384OakRidge-15.jpg', //
        './photos/1384OakRidge-16.jpg',
        './photos/1384OakRidge-17.jpg'
    ]
};